### ISSUE TITLE
Surroundings: FE - Be able to display a map of the island

### ISSUE THREAD

**Issue by Joralf** [WeCamp/island-of-the-dead#32]
In order to see my whereabouts
As a player
I want to see a map with my current location on it
- [ ] draw google maps in the viewport
- [x] fetch the player's coordinates from GPS

**Comment by jencockers** [comment]
Unable to view coordinates from the GPS API on Chrome. Need to set HTTPS option on node.

`getCurrentPosition() and watchPosition() no longer work on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.`
